### ISSUE TITLE
starting to get error

### ISSUE THREAD

**Issue by SilentWarrior1** [postal9191/Cosmo_Miner#3]
Greetings, again)
```
Exception in thread Thread-2 (start_spin_thread):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "J:\Telegram\Cosmo_Miner-main\main.py", line 16, in start_spin_thread
    spin.spinRun()
  File "J:\Telegram\Cosmo_Miner-main\spin.py", line 136, in spinRun
    lastSpinDate = datetime.fromisoformat(lastSpinDate.replace('Z', '+00:00'))
                                          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```
or maybe this is due to spin-maintance?

**Comment by postal9191** [comment]
will fall because the site went to "technical works" or we were simply banned, there is no way to check

**Comment by postal9191** [comment]
Fix bug
